import type { CompanyNewsData, CompanyNewsItem } from "@/types/news";
import { calculateNewsSentimentScore } from "./news-score";

const asOf = "2026-07-03T21:00:00.000Z";

const newsItems: CompanyNewsItem[] = [
  {
    id: "news-apxt-1",
    ticker: "APXT",
    companyId: "apex-technologies",
    title: "Apex Technologies lifts full-year cloud revenue outlook",
    source: "Mock Market Wire",
    url: "https://news.example.com/apxt-cloud-outlook",
    publishedAt: "2026-06-28T14:30:00.000Z",
    summary: "Management cited stronger enterprise renewals and higher attach rates for analytics modules.",
    sentiment: "positive",
    eventType: "guidance",
    severity: "medium",
    relevanceScore: 0.94,
    confidenceScore: 0.88,
    riskImpact: "positive",
  },
  {
    id: "news-apxt-2",
    ticker: "APXT",
    companyId: "apex-technologies",
    title: "Apex launches compliance automation product for regulated customers",
    source: "Mock Tech Brief",
    url: "https://news.example.com/apxt-compliance-launch",
    publishedAt: "2026-06-17T11:00:00.000Z",
    summary: "The new module targets financial services and healthcare accounts with audit workflow automation.",
    sentiment: "positive",
    eventType: "product",
    severity: "low",
    relevanceScore: 0.82,
    confidenceScore: 0.84,
    riskImpact: "positive",
  },
  {
    id: "news-apxt-3",
    ticker: "APXT",
    companyId: "apex-technologies",
    title: "Analysts flag valuation sensitivity after software sector rally",
    source: "Mock Research Desk",
    url: "https://news.example.com/apxt-sector-valuation",
    publishedAt: "2026-05-30T16:45:00.000Z",
    summary: "Sector multiples remain elevated, but balance-sheet quality is viewed as a relative strength.",
    sentiment: "neutral",
    eventType: "analyst_rating",
    severity: "low",
    relevanceScore: 0.72,
    confidenceScore: 0.8,
    riskImpact: "neutral",
  },
  {
    id: "news-rrgi-1",
    ticker: "RRGI",
    companyId: "redstone-retail",
    title: "Redstone Retail seeks covenant waiver after weak quarter",
    source: "Mock Credit Journal",
    url: "https://news.example.com/rrgi-covenant-waiver",
    publishedAt: "2026-06-26T13:15:00.000Z",
    summary: "The retailer opened discussions with lenders after same-store sales and EBITDA missed plan.",
    sentiment: "negative",
    eventType: "debt",
    severity: "high",
    relevanceScore: 0.96,
    confidenceScore: 0.9,
    riskImpact: "negative",
  },
  {
    id: "news-rrgi-2",
    ticker: "RRGI",
    companyId: "redstone-retail",
    title: "Redstone announces accelerated store closures",
    source: "Mock Retail Daily",
    url: "https://news.example.com/rrgi-store-closures",
    publishedAt: "2026-06-12T10:20:00.000Z",
    summary: "Management plans to close 90 locations and reduce fixed costs over the next two quarters.",
    sentiment: "neutral",
    eventType: "restructuring",
    severity: "medium",
    relevanceScore: 0.88,
    confidenceScore: 0.86,
    riskImpact: "neutral",
  },
  {
    id: "news-rrgi-3",
    ticker: "RRGI",
    companyId: "redstone-retail",
    title: "Supplier payment delays widen during liquidity review",
    source: "Mock Supply Chain Watch",
    url: "https://news.example.com/rrgi-supplier-delays",
    publishedAt: "2026-05-24T09:10:00.000Z",
    summary: "Several vendors reportedly tightened terms as Redstone works through a cash conservation plan.",
    sentiment: "negative",
    eventType: "debt",
    severity: "high",
    relevanceScore: 0.9,
    confidenceScore: 0.82,
    riskImpact: "negative",
  },
  {
    id: "news-nvbs-1",
    ticker: "NVBS",
    companyId: "novara-biosciences",
    title: "Novara audit committee reviews revenue recognition controls",
    source: "Mock BioPharma Ledger",
    url: "https://news.example.com/nvbs-audit-review",
    publishedAt: "2026-06-29T15:05:00.000Z",
    summary: "The review follows questions about customer concentration and collection timing in specialty therapeutics.",
    sentiment: "negative",
    eventType: "accounting_issue",
    severity: "critical",
    relevanceScore: 0.98,
    confidenceScore: 0.87,
    riskImpact: "negative",
  },
  {
    id: "news-nvbs-2",
    ticker: "NVBS",
    companyId: "novara-biosciences",
    title: "Novara CFO to step down after year-end close",
    source: "Mock Governance Monitor",
    url: "https://news.example.com/nvbs-cfo-transition",
    publishedAt: "2026-06-20T18:30:00.000Z",
    summary: "The company said the transition is unrelated to the ongoing audit committee review.",
    sentiment: "negative",
    eventType: "management_change",
    severity: "medium",
    relevanceScore: 0.89,
    confidenceScore: 0.83,
    riskImpact: "negative",
  },
  {
    id: "news-nvbs-3",
    ticker: "NVBS",
    companyId: "novara-biosciences",
    title: "Specialty therapeutic receives expanded reimbursement coverage",
    source: "Mock Healthcare Market",
    url: "https://news.example.com/nvbs-coverage",
    publishedAt: "2026-05-21T12:40:00.000Z",
    summary: "The coverage decision may support reported revenue growth if collection trends normalize.",
    sentiment: "positive",
    eventType: "product",
    severity: "medium",
    relevanceScore: 0.78,
    confidenceScore: 0.81,
    riskImpact: "positive",
  },
  {
    id: "news-cscm-1",
    ticker: "CSCM",
    companyId: "cascade-manufacturing",
    title: "Cascade order backlog improves as industrial demand recovers",
    source: "Mock Industrial Times",
    url: "https://news.example.com/cscm-backlog",
    publishedAt: "2026-06-24T14:05:00.000Z",
    summary: "The manufacturer reported stronger infrastructure and equipment orders versus the prior quarter.",
    sentiment: "positive",
    eventType: "earnings",
    severity: "medium",
    relevanceScore: 0.9,
    confidenceScore: 0.86,
    riskImpact: "positive",
  },
  {
    id: "news-cscm-2",
    ticker: "CSCM",
    companyId: "cascade-manufacturing",
    title: "Cascade refinances term loan at fixed rate",
    source: "Mock Credit Journal",
    url: "https://news.example.com/cscm-refinancing",
    publishedAt: "2026-06-07T10:15:00.000Z",
    summary: "The transaction reduces floating-rate exposure and extends the maturity wall by three years.",
    sentiment: "positive",
    eventType: "debt",
    severity: "medium",
    relevanceScore: 0.84,
    confidenceScore: 0.88,
    riskImpact: "positive",
  },
  {
    id: "news-cscm-3",
    ticker: "CSCM",
    companyId: "cascade-manufacturing",
    title: "Steel input costs remain volatile",
    source: "Mock Macro Desk",
    url: "https://news.example.com/cscm-steel-costs",
    publishedAt: "2026-05-19T09:25:00.000Z",
    summary: "Commodity price moves may pressure margins if demand softens again.",
    sentiment: "neutral",
    eventType: "macro",
    severity: "low",
    relevanceScore: 0.68,
    confidenceScore: 0.78,
    riskImpact: "neutral",
  },
  {
    id: "news-mdhs-1",
    ticker: "MDHS",
    companyId: "meridian-health",
    title: "Meridian Health cuts margin outlook on labor cost pressure",
    source: "Mock Healthcare Ledger",
    url: "https://news.example.com/mdhs-margin-outlook",
    publishedAt: "2026-06-25T12:10:00.000Z",
    summary: "Management lowered EBITDA margin expectations as contract nursing costs remain elevated.",
    sentiment: "negative",
    eventType: "guidance",
    severity: "medium",
    relevanceScore: 0.92,
    confidenceScore: 0.87,
    riskImpact: "negative",
  },
  {
    id: "news-mdhs-2",
    ticker: "MDHS",
    companyId: "meridian-health",
    title: "Meridian starts payer contract renegotiation program",
    source: "Mock Provider Weekly",
    url: "https://news.example.com/mdhs-payer-renegotiation",
    publishedAt: "2026-06-10T15:00:00.000Z",
    summary: "The initiative is designed to offset reimbursement pressure across acute-care facilities.",
    sentiment: "neutral",
    eventType: "restructuring",
    severity: "medium",
    relevanceScore: 0.82,
    confidenceScore: 0.84,
    riskImpact: "neutral",
  },
  {
    id: "news-mdhs-3",
    ticker: "MDHS",
    companyId: "meridian-health",
    title: "Analysts maintain cautious view on hospital operators",
    source: "Mock Research Desk",
    url: "https://news.example.com/mdhs-analyst-view",
    publishedAt: "2026-05-26T17:20:00.000Z",
    summary: "Higher wages and payer mix shifts are expected to keep sector margins under pressure.",
    sentiment: "negative",
    eventType: "analyst_rating",
    severity: "low",
    relevanceScore: 0.74,
    confidenceScore: 0.8,
    riskImpact: "negative",
  },
];

const companyNamesByTicker: Record<string, { companyId: string; companyName: string }> = {
  APXT: { companyId: "apex-technologies", companyName: "Apex Technologies" },
  RRGI: { companyId: "redstone-retail", companyName: "Redstone Retail Group" },
  NVBS: { companyId: "novara-biosciences", companyName: "Novara BioSciences" },
  CSCM: { companyId: "cascade-manufacturing", companyName: "Cascade Manufacturing" },
  MDHS: { companyId: "meridian-health", companyName: "Meridian Health Systems" },
};

export function getMockNewsByTicker(ticker: string): CompanyNewsItem[] {
  const normalizedTicker = ticker.trim().toUpperCase();
  return newsItems
    .filter((item) => item.ticker === normalizedTicker)
    .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
}

export function getMockNewsDataByTicker(ticker: string): CompanyNewsData | undefined {
  const normalizedTicker = ticker.trim().toUpperCase();
  const company = companyNamesByTicker[normalizedTicker];

  if (!company) return undefined;

  const items = getMockNewsByTicker(normalizedTicker);

  return {
    ticker: normalizedTicker,
    companyId: company.companyId,
    companyName: company.companyName,
    provider: "mock",
    asOf,
    items,
    sentiment: calculateNewsSentimentScore(normalizedTicker, items, asOf),
  };
}

export const mockNewsData = Object.keys(companyNamesByTicker)
  .map(getMockNewsDataByTicker)
  .filter((item): item is CompanyNewsData => Boolean(item));
